module.exports = [
  {
    id: 1,
    name: "i5",
    brand: "Intel",
    model: "13600k",
    category: "cpu",
    description: "13th gen Intel cpu",
  },
  {
    id: 2,
    name: "i7",
    brand: "Intel",
    model: "13700k",
    category: "cpu",
    description: "13th gen Intel cpu",
  },
  {
    id: 3,
    name: "i9",
    brand: "Intel",
    model: "13900k",
    category: "cpu",
    description: "13th gen Intel cpu",
  },
  {
    id: 4,
    name: "i5",
    brand: "Intel",
    model: "14600k",
    category: "cpu",
    description: "14th gen Intel cpu",
  },
  {
    id: 5,
    name: "i7",
    brand: "Intel",
    model: "14700k",
    category: "cpu",
    description: "14th gen Intel cpu",
  },
  {
    id: 6,
    name: "i9",
    brand: "Intel",
    model: "14900k",
    category: "cpu",
    description: "14th gen Intel cpu",
  },
];
